# Generated by Django 3.0.5 on 2020-04-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
