# Generated by Django 3.0.5 on 2020-04-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200416_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='major',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='university',
        ),
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
